### ISSUE TITLE
0.3 Alpha crashed if CC is not installed.

### ISSUE THREAD

**Issue by brisingraerowing** [latibro/Automation-Mod#18]
[Crash Log](https://gist.github.com/BrisingrAerowing/768d4c99aab1dbc966e70b3fcd5859c0)

I'd presume it's [this class](https://github.com/latibro/Automation-Mod/blob/forge-1.12.2/src/main/groovy/latibro/automation/integration/computercraft/TileEntityPeripheralProvider.groovy) at fault.

**Comment by latibro** [comment]
Agh bummer... have I re-introduced that error that ComputerCraft i not completely optional.

Can you confirm that you don't have any ComputerCraft mod (like CC:Tweaker installed)

**Comment by latibro** [comment]
Stange... I'm not able to recreate the problem... if I leave out the CC:Tweaked mod.  
  
Are you able to give me some more insides of when the crash happens?  
\- Is is while booting?  
\- While loading the world?  
\- While placing a block  
Or when does this happen?

Also be aware that you are using a alpha version (alpha means that features for this version is not yet complete), the latest beta might be more stabel (0.2.0) (beta means features are complete for this version, but there might still be bugs)

**Comment by brisingraerowing** [comment]
I don't have CC:Tweaked installed either.

This occurs during game startup.

I'll test the 0.2.0 version.

**Comment by latibro** [comment]
Hmm... stange that I'm not able to recreate it with 0.3.0-alpha.1

Do you have you modpack available for download somewhere that I can try it out from that?

Or you could join my Discord channel, that would make it easier for me to help you out here - https://discord.gg/W6UxS3vDfb

**Comment by latibro** [comment]
Found and fixed the problem - will push a 0.3.0-alpha.2 later tonight

**Comment by latibro** [comment]
Fix included in 0.3.0-alpha.2 which has been pushed to CurseForge
